"""empty message

Revision ID: 4afd862e0c89
Revises: af666a89aca0
Create Date: 2022-09-14 16:35:31.210182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afd862e0c89'
down_revision = 'af666a89aca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['desc'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###
