"""empty message

Revision ID: 6218fd805d75
Revises: 
Create Date: 2022-09-13 20:48:20.123254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6218fd805d75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
